/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package studentmanagement;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Madhav Gupta
 */
public class View extends javax.swing.JFrame {

    /**
     * Creates new form View
     */
    public View(){
        initComponents();
        try{
        jComboBoxbranch.setSelectedIndex(-1);
        jComboBoxyear.setSelectedIndex(-1);
        jComboBoxsection.setSelectedIndex(-1);
        }
        catch(Exception ex)
        {
            System.out.println("oops");
        }
        
        
    }
    //Other Functions copied
    
    public Connection getConnection() throws SQLException
    {
        Connection con;
        con=DriverManager.getConnection("jdbc:mysql://localhost:3306/student","root","");
        return con;
    }
    public ArrayList<Student> getStudents() throws SQLException
    {
        ArrayList<Student> list=new ArrayList<>();
        Connection connection=getConnection();
        Statement st;
        ResultSet rs;
        String query="Select * from student where branch='"+branch+"' and year="+year1+" and section="+section1;
        st=connection.createStatement();
        rs=st.executeQuery(query);
        while(rs.next())
        {
           Student stu=new Student(rs.getInt(1),rs.getString(2),rs.getDate(3),rs.getString(4));
           list.add(stu);
        }
        return list;
    }
    public void Show_in_table(JTable student) throws SQLException
    {
        ArrayList<Student> list=getStudents();
        //Just To do the table 
        DefaultTableModel model=(DefaultTableModel)student.getModel();
        Object[] row=new Object[4];
        for(int i=0;i<list.size();i++)
        {
            row[0]=list.get(i).getRollno();
            row[1]=list.get(i).getName();
            row[2]=list.get(i).getDate();
            row[3]=list.get(i).getFname();
            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jStudentsDetails = new javax.swing.JTable();
        jComboBoxbranch = new javax.swing.JComboBox<>();
        jComboBoxyear = new javax.swing.JComboBox<>();
        jComboBoxsection = new javax.swing.JComboBox<>();
        jbtngo = new javax.swing.JButton();
        jNamec = new javax.swing.JLabel();
        jRollno1 = new javax.swing.JLabel();
        jNamec1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 255, 255));

        jStudentsDetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Roll Number", "Name", "Date Of Birth", "Father's Name"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jStudentsDetails);
        if (jStudentsDetails.getColumnModel().getColumnCount() > 0) {
            jStudentsDetails.getColumnModel().getColumn(3).setMinWidth(135);
            jStudentsDetails.getColumnModel().getColumn(3).setPreferredWidth(130);
            jStudentsDetails.getColumnModel().getColumn(3).setMaxWidth(140);
        }

        jComboBoxbranch.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CS", "IT", "EC", "EE", "CE", "ME" }));
        jComboBoxbranch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxbranchActionPerformed(evt);
            }
        });

        jComboBoxyear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4" }));

        jComboBoxsection.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3" }));

        jbtngo.setText("Go");
        jbtngo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtngoActionPerformed(evt);
            }
        });

        jNamec.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jNamec.setText("Section :");

        jRollno1.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jRollno1.setText("Branch :");

        jNamec1.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jNamec1.setText("Year :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jRollno1)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBoxbranch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(jNamec1)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBoxyear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jNamec)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBoxsection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(jbtngo)))
                .addContainerGap(168, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxbranch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxyear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxsection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtngo)
                    .addComponent(jRollno1)
                    .addComponent(jNamec)
                    .addComponent(jNamec1))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(76, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxbranchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxbranchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxbranchActionPerformed

    private void jbtngoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtngoActionPerformed
        branch=(String)jComboBoxbranch.getSelectedItem();
        year=(String)jComboBoxyear.getSelectedItem();
        section=(String)jComboBoxsection.getSelectedItem();
        if(year!=null && section!=null)
        {
        year1=Integer.parseInt(year);
        section1=Integer.parseInt(section);
        }
            try {
                DefaultTableModel model=(DefaultTableModel)jStudentsDetails.getModel();
                model.setRowCount(0);
                Show_in_table(jStudentsDetails);
            } catch (SQLException ex) {
                Logger.getLogger(Insert.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_jbtngoActionPerformed

    /**
     * @param args the command line arguments
     * @throws java.sql.SQLException
     */
    public static void main(String args[]) throws SQLException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                    new View().setVisible(true);
            }
        });
    }

    //Variables used for our purpose
    String year;
    String branch;
    String section;
    int year1;
    int section1;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBoxbranch;
    private javax.swing.JComboBox<String> jComboBoxsection;
    private javax.swing.JComboBox<String> jComboBoxyear;
    private javax.swing.JLabel jNamec;
    private javax.swing.JLabel jNamec1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jRollno1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jStudentsDetails;
    private javax.swing.JButton jbtngo;
    // End of variables declaration//GEN-END:variables


}
